modLoader="javafml"
loaderVersion="[47,)"
license="AGPL-3.0-or-later"
issueTrackerURL="https://github.com/better-content/better-airtight-machines/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Better Content"
displayURL="https://github.com/better-content/better-airtight-machines"
description='''
Adds a removable airtight upgrade for Create Basins and PneumaticCraft gas machines.
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version},1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="better_chemlib_hazards"
mandatory=true
versionRange="[0.2.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="chemlib"
mandatory=true
versionRange="[2.0.19,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="pneumaticcraft"
mandatory=true
versionRange="[6.0.22,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
mandatory=true
versionRange="[6.0.8,)"
ordering="AFTER"
side="BOTH"
